name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - release-*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # HACK: Force a TTY to enable browser-driver-manager to manipulate stdout.
      - shell: 'script -q -e -c "bash {0}"'
        run: npx browser-driver-manager install chromedriver --verbose
      - run: gem install bundler
      - run: rake bootstrap
      # unit test - API
      - run: rake test_unit\[axe-core-api\]
      # unit test - webdrivers
      - run: rake test_unit\[axe-core-selenium\]
      - run: rake test_unit\[axe-core-watir\]
      - run: rake test_unit\[axe-core-capybara\]
      # unit test - framework integrations
      - run: rake test_unit\[axe-core-cucumber\]
      - run: rake test_unit\[axe-core-rspec\]
      # e2e test - rspec -> capybara
      - run: |
          cd packages/axe-core-rspec && cd e2e/capybara
          bundle install && bundle exec rspec
      # e2e test - cucumber -> capybara
      - run: |
          cd packages/axe-core-cucumber && cd e2e/capybara
          bundle install && bundle exec cucumber
      # e2e test - cucumber -> watir
      - run: |
          cd packages/axe-core-cucumber && cd e2e/watir
          bundle install && bundle exec cucumber
      # e2e test - selenium, axe 4.3.x
      - run: |
          npm i
          cd node_modules/axe-test-fixtures/fixtures && python3 -m http.server &
          sleep 1 # Just wait a bit for the http server to startup
          cd packages/axe-core-api/e2e/selenium
          bundle install && bundle exec rspec
